version: '2'
services:
  cyberq:
    build: .
    ports:
      - 8000:8000
  prometheus:
    build: prometheus
    ports:
      - "127.0.0.1:9090:9090"
  grafana:
    image: grafana/grafana
    ports:
      - "127.0.0.1:3000:3000"
