version: '2'
services:
  cyberq:
    build: .
    ports:
      - 8000:8000
  prometheus:
    build: prometheus
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - type: volume
        source: prom_data
        target: /prometheus
  grafana:
    image: grafana/grafana
    ports:
      - "127.0.0.1:3000:3000"
volumes:
  prom_data:
